// Re-export Prisma-generated model types for use throughout the app.
// Types are auto-generated by `prisma generate` from prisma/schema.prisma.
export type { User, Plan, Subscription, Payment, Account } from "@prisma/client";
